name: Octopus MinMax Bot
version: 0.1.1
slug: octopus-minmax-bot
description: A bot to automatically compare and switch smart electricity tariffs on Octopus Energy
arch:
  - armhf
  - armv7
  - amd64
  - aarch64
options:
  one_off: false
  discord_webhook: ""
  execution_time: "23:00"
  octopus_password: ""
  octopus_email: ""
  api_key: ""
  acc_number: ""
schema:
  one_off: bool
  discord_webhook: str
  execution_time: str
  octopus_password: password
  octopus_email: str
  api_key: str
  acc_number: str
image: eelmafia/octopus-minmax-bot:latest