---
name: Octopus MinMax Bot
image: eelmafia/octopus-minmax-bot
url: https://github.com/eelmafia/octopus-minmax
version: v0.7.2
slug: octopus_minmax_bot
startup: application
init: false
description: A bot to automatically compare and switch smart electricity tariffs on Octopus Energy
arch:
  - armhf
  - armv7
  - amd64
  - aarch64
options:
  one_off: false
  notification_url: ""
  execution_time: "23:00"
  api_key: "API KEY HERE"
  acc_number: "ACC NUMBER HERE"
schema:
  one_off: bool
  notification_url: str
  execution_time: str
  api_key: str
  acc_number: str
