---
name: Octopus MinMax Bot
image: eelmafia/octopus-minmax-bot
url: https://github.com/eelmafia/octopus-minmax
version: v0.7.2
slug: octopus_minmax_bot
startup: application
init: false
legacy: true
description: A bot to automatically compare and switch smart electricity tariffs on Octopus Energy
arch:
  - armhf
  - armv7
  - amd64
  - aarch64
options:
  api_key: "API KEY HERE"
  acc_number: "ACC NUMBER HERE"
  execution_time: "23:00"
  one_off: false
  dry_run: false
  notification_urls: ""
  tariffs: "agile,go,flexible"
  tz: "Europe/London"
schema:
  api_key: str
  acc_number: str
  execution_time: str
  one_off: bool
  dry_run: bool
  notification_urls: str
  tariffs: str
  tz: str
environment:
  API_KEY: "{api_key}"
  ACC_NUMBER: "{acc_number}"
  EXECUTION_TIME: "{execution_time}"
  ONE_OFF: "{one_off}"
  DRY_RUN: "{dry_run}"
  NOTIFICATION_URLS: "{notification_urls}"
  TARIFFS: "{tariffs}"
  TZ: "{tz}"
  PYTHONUNBUFFERED: "1"
