# name: Daily Run

# on:
#   schedule:
#     - cron: "00 23 * * *"
#   workflow_dispatch:

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     container:
#       image: mcr.microsoft.com/playwright/python:v1.47.0-noble
#       options: --user 1001
#     # Add repository secrets to the workflow as environment variables
#     env:
#       API_KEY: ${{ secrets.API_KEY }}
#       ACC_NUMBER: ${{ secrets.ACC_NUMBER }}
#       BASE_URL: ${{ secrets.BASE_URL }}
#       DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
#       OCTOPUS_LOGIN_EMAIL: ${{ secrets.OCTOPUS_LOGIN_EMAIL }}
#       OCTOPUS_LOGIN_PASSWD: ${{ secrets.OCTOPUS_LOGIN_PASSWD }}
#     steps:
#     - uses: actions/checkout@v4
#     - name: Set up Python 3.10
#       uses: actions/setup-python@v3
#       with:
#         python-version: '3.10'
#     - name: Install dependencies
#       run: |
#         python3 -m pip install -r requirements.txt
#     - name: Run Octopus Minmax Bot 🐙🤖
#       run: |
#         python3 ./main.py
